export const WEATHER_API_URL = `
  https://api.open-meteo.com/v1/forecast
  ?latitude=52.52
  &longitude=13.41
  &current=
    temperature_2m,
    relative_humidity_2m,
    apparent_temperature,
    is_day,
    precipitation,
    rain,
    showers,
    snowfall,
    weather_code,
    cloud_cover,
    wind_speed_10m,
    wind_direction_10m,
    wind_gusts_10m
  &hourly=
    temperature_2m,
    relative_humidity_2m,
    dew_point_2m,
    apparent_temperature,
    precipitation_probability,
    precipitation,
    rain,
    showers,
    snowfall,
    snow_depth,
    cloud_cover,
    visibility,
    wind_speed_10m,
    wind_gusts_10m
  &daily=
    sunrise,
    sunset
  &forecast_days=1
`;
