import type { Metadata } from "next";
import { Inter, Roboto, Inconsolata } from "next/font/google";
import cx from 'classnames';
import "./globals.css";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const roboto = Roboto({
  weight: '100',
  subsets: ['latin'],
  variable: '--font-roboto',
});

const inconsolata = Inconsolata({
  subsets: ['latin'],
  variable: '--font-inconsolata',
});

export const metadata: Metadata = {
  title: "rainbox.world",
  description: "generated by lilly wolf",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>☁️</text></svg>" />
      <body className={cx([inconsolata.className, inter.variable, roboto.variable])}>
        {children}
      </body>
    </html>
  );
}
